-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 11:32:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestionSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestionSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionSystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gestionSystem` ;

-- -----------------------------------------------------
-- Table `gestionSystem`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionSystem`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cellphone` INT NOT NULL,
  `direction` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionSystem`.`machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionSystem`.`machine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NOT NULL,
  `serial_number` INT NOT NULL,
  `status` ENUM('AVAILABLE', 'RENTED') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionSystem`.`rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionSystem`.`rent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rent_start_date` DATE NOT NULL,
  `rent_finish_date` DATE NOT NULL,
  `client_id` INT NOT NULL,
  `machine_id` INT NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rent_client` (`client_id` ASC) VISIBLE,
  INDEX `fk_rent_machine` (`machine_id` ASC) VISIBLE,
  CONSTRAINT `fk_rent_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `gestionSystem`.`client` (`id`),
  CONSTRAINT `fk_rent_machine`
    FOREIGN KEY (`machine_id`)
    REFERENCES `gestionSystem`.`machine` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
